version: '3.3'

services:
  db-healthblog:
    image: mariadb
    container_name: db-healthblog
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=geheimhealth
    expose:
      - 3306
    volumes:
      - ./db:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-healthblog
    restart: always
    ports:
      - 5101:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  flask:
    image: snickch/flask001:v2
    container_name: flask-healthblog
    restart: always
    ports:
        - 5100:5100
    volumes:
      - ./app:/app
    command: gunicorn -w 4 --bind 0.0.0.0:5100 wsgi:app
    depends_on:
      - "db-healthblog"

    
  adminer:
    image: adminer
    container_name: adminer-healthblog
    ports:
     - 5150:8080
    environment:
     - ADMINER_DEFAULT_SERVER=db-healthblog     
